Resources:
    Ec2Instance:
        Type: 'AWS::EC2:Ec2Instance'
        Properties:
            InstanceType: t2.micro
            ImageId: ami-07c8bc5c1ce9598c3
            Tags:
              - Key: Name
                Value: A simple example